        <fieldset data-amd="modules/page/block">
            <legend><?php echo $this->gabarit->getLabel(); ?></legend>
            <div style="display:none;">
                <div class="expand-collapse pull-right">
                    <a href="#" class="expand disabled">Tout déplier</a> / <a href="#" class="collapse">Tout replier</a>
                </div>
                <div data-amd="modules/helper/sortable">
<?php
    foreach ($this->values as $value) {
        if (count($this->values) == 1
            && (!isset($value['id']) || $value['id'] == 0)
        ) {
            $visible = true;
        } else {
            $visible = $value['visible'];
        }

        $this->buildChamps($value);
?>
                    <fieldset class="block-to-sort block-to-duplicate">
                        <legend><?php echo $this->valueLabel; ?></legend>

                        <div>
                            <div class="line" style="display:none;">
                                <label for="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>">Visible</label>
                                <input type="checkbox" id="visible-<?php echo $this->gabarit->getId() . '-' . (isset($value['id']) ? $value['id'] : 0) . '-' . (isset($value['id_version']) ? $value['id_version'] : 1) ?>" class="changevisible"<?php echo $visible ? ' checked="checked"' : ''; ?> />
                                <input type="hidden" value="<?php echo $visible ? 1 : 0; ?>" name="visible[]" />
                            </div>

                            <div<?php echo $visible ? '' : ' class="translucide"'; ?>>
                                <input type="hidden" name="id_<?php echo $this->gabarit->getTable() . '[]" value="' . (isset($value['id']) ? $value['id'] : '') ?>" />

                                <?php echo $this->champsHTML; ?>
                            </div>
                        </div>
                        <div style="float:left; margin-left:8px;">
                            <div class="btn-toolbar">
                                <div class="btn-group btn-bloc-action">
                                    <a href="#" class="btn btn-sm btn-info block-to-sort-handle <?php echo ( count($this->values) > 1 ? '' : 'to-remove' ) ?>" title="Déplacer" <?php echo ( count($this->values) > 1 ? '' : ' style="display: inline-bloc;"' ) ?>><i class="fa fa-retweet"></i></a>
                                    <a href="#" class="btn btn-sm exec-onclick-togglevisible<?php echo $visible ? ' btn-success' : ' btn-default'; ?>" title="Visible sur le site"><i class="fa <?php echo $visible ? 'fa-eye' : 'icon-eye-slash'; ?>"></i></a>
                                    <button type="button" class="btn btn-sm btn-warning exec-onclick-removeblock" title="Supprimer" <?php echo ( count($this->values) > 1 ? '' : ' disabled"' ) ?>><i class="fa fa-trash"></i></button>
                                </div>
                            </div>
                        </div>
                    </fieldset>
<?php
    }
?>
                </div>
                <button class="btn btn-sm btn-info exec-onclick-addblock">
                    <i class="fa fa-plus"></i> Ajouter un bloc &laquo; <?php echo $this->gabarit->getLabel(); ?> &raquo;
                </button>
            </div>
        </fieldset>