<div class="line form-line">
    <div class="line">
        <label for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?><?php echo in_array('form-oblig', explode(" ", $this->classes)) ? ' <span class="required">*</span>' : '' ; ?></span>
        </label>
        <input type="text" style="width:<?php echo $this->params['WIDTH']; ?>px;" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?>" value="<?php echo $this->value; ?>" />
    </div>

    <div class="line form-other-line" style="display:none;">
        <label class="form-other-flag"></label>
        <input type="text" readonly="readonly" class="form-other-elmt" />
    </div>
</div>
