<div class="line form-line" data-toggle="popover" data-trigger="hover" title="Aide" data-html="true"  data-popover-content="#aide-champ<?php echo $this->champ['id']; ?>">
    <div class="line form-group">
        <label class="col-sm-3 control-label" for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?><?php echo in_array('form-oblig', explode(' ', $this->classes)) ? ' <span class="required">*</span>' : '' ; ?></span>
        </label>
        <div class="col-sm-9">
            <input <?php echo $this->champ['typedonnee'] == 'DATE' ? 'data-amd="modules/helper/datepicker"' : '' ?> type="text" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="form-control <?php echo $this->classes; ?>" value="<?php echo $this->value; ?>" />
        </div>
    </div>

    <div class="line form-other-line form-group" style="display:none;">
        <label class="form-other-flag col-sm-3 control-label"></label>
        <div class="col-sm-9">
            <input type="text" readonly="readonly" class="form-other-elmt form-control">
        </div>
    </div>
</div>