variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Paris"

before_script:
# Install composer
  - curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
  - php composer.phar install

php-5.6:
  image: tetraweb/php:5.6
  script:
    - vendor/bin/atoum -d tests -bf tests/units/.bootstrap.atoum.php

php-7.0:
  image: tetraweb/php:7.0
  script:
    - vendor/bin/atoum -d tests -bf tests/units/.bootstrap.atoum.php
  allow_failure: true
