<?php
/**
 * Affichage du rapport d'erreur Marvin
 *
 * @author  Adrien <aimbert@solire.fr>
 * @license CC by-nc http://creativecommons.org/licenses/by-nc/3.0/fr/
 */
?>
<html>
  <body bgcolor="<?php echo $this->color5; ?>" text="#000000">
    <div style="width:70%; margin-left:15%; margin-right:15%; margin-top:50px; border-radius:4px; background:<?php echo $this->color2; ?>; border-radius:4px 4px 0px 0px; border: 1px solid <?php echo $this->color1; ?>;">
      <div style="width:100%; background:<?php echo $this->color4; ?>; border-radius:4px 4px 0px 0px; color:<?php echo $this->color5; ?>; font-weight:bold; font-size:1.3em; text-align:right;">
        <span style="padding-right:30px;">Rapport d'erreur</span>
      </div>
      <div style="width:100%; background:#FFFFFF; min-height:300px;">
        <div style="width:288px; height:300px; float:left;">
          <img src="http://thingsiamobsessedwithtoday.files.wordpress.com/2011/07/marvin.jpg" alt="Marvin" border="0">
        </div>
        <div style="padding-top:20px; padding-right:20px;">
          <p style="background:#D9D9D9; border-radius:4px; font-size:1.8em; margin-left:300px; padding:15px;">
            <span style="font-size:1em; color:<?php echo $this->color3; ?>;"><</span>
            J'ai un profond manque de plaisir de ne pouvoir éviter de vous annoncer qu'une erreur est survenue.
            <span style="font-size:1em; color:<?php echo $this->color3; ?>;">></span>
          </p>
        </div>
      </div>
      <div style="width:100%; color:#FFF;padding:1%">
        <div style="padding:5px;">
            <div style="font-style:italic; margin-bottom:10px; border:1px solid #D9D9D9; border-radius: 4px 0px 4px 0px; max-width:97%; ">
                <div style="background:<?php echo $this->color3; ?>; font-weight:bold; font-size:1em; font-style:none; padding-left:20px;">
                    <?php echo $this->exc->getFile(); ?> &raquo; <span><?php echo $this->exc->getLine(); ?></span>
                </div>
                <div style="font-size:1.5em;"><?php echo $this->exc->getMessage(); ?></div>
                <div style="color:#fff; max-width:80%; margin-left:10%;  border-radius: 4px 0px 4px 0px;margin-bottom:10px;  border:1px solid #D9D9D9; padding-left:2%;">
                    <?php echo $this->readLines($this->exc->getFile(), $this->exc->getLine()); ?>
                </div>
            </div>
<?php if (isset($this->data) && !empty($this->data)) { ?>
            <h2>Data</h2>
            <div style="padding:5px;">
    <?php foreach ($this->data as $data) { ?>
                <div style="font-style:italic; margin-bottom:10px; border:1px solid #D9D9D9; border-radius: 4px 0px 4px 0px; max-width:97%;">
                    <div style="background:<?php echo $this->color3; ?>; font-weight:bold; font-style:none; padding-left:20px;"><?php echo $data['key'] ?></div>
                    <?php echo $data['value'] ?>
                </div>
    <?php } // foreach $this->request ?>
            </div>
<?php } // If $this->request ?>
<?php if (isset($this->request) && !empty($this->request)) { ?>
            <h2>Request</h2>
            <div style="padding:5px;">
    <?php foreach ($this->request as $req) { ?>
                <div style="font-style:italic; margin-bottom:10px; border:1px solid #D9D9D9; border-radius: 4px 0px 4px 0px; max-width:97%;">
                    <div style="background:<?php echo $this->color3; ?>; font-weight:bold; font-style:none; padding-left:20px;">[<?php echo $req['loc'] ?>] <?php echo $req['key'] ?></div>
                    <?php echo $req['value'] ?>
                </div>
    <?php } // foreach $this->request ?>
            </div>
<?php } // If $this->request ?>
<?php if (isset($this->trace) && !empty($this->trace)) { ?>
            <h2>Trace</h2>
            <div style="padding:5px;">
    <?php foreach ($this->trace as $trace) { ?>
                <div style="font-style:italic; margin-bottom:10px; border:1px solid #D9D9D9; border-radius: 4px 0px 4px 0px;max-width:97%; ">
                    <div style="background:<?php echo $this->color3; ?>; font-weight:bold; font-size:1em; font-style:none; padding-left:20px;">
                        <?php echo $trace['file']; ?> &raquo; <?php echo $trace['line']; ?>
                    </div>
                    <h3><?php echo $trace['function']; ?>()</h3>
                    <div style="padding-left:5%;">
        <?php foreach ($trace['args'] as $arg) { ?>
                        <div style="font-style:italic; margin-bottom:10px;">
                            <?php echo $arg; ?>
                        </div>
        <?php } // foreach $this->trace['args'] ?>
                    </div>
                    <div style="color:#fff; max-width:80%; margin-left:10%; border-radius: 4px 0px 4px 0px;margin-bottom:10px; border:1px solid #D9D9D9; padding-left:2%;">
                        <?php echo $trace['showFile']; ?>
                    </div>
                </div>
    <?php } // foreach $this->trace ?>
<?php } // If $this->trace ?>
      </div>
    </div>
  </body>
</html>
