<form data-response="<?php echo (isset($this->modeEdit) && $this->modeEdit ? 'edit' : 'add') ?>" class="form-horizontal datatable-form <?php echo (isset($this->modeEdit) && $this->modeEdit ? 'edit' : 'add') ?>" method="post" action="<?php echo $this->url; ?><?php echo strpos($this->url, "?") === false ? '?' : '&' ?><?php echo (isset($this->modeEdit) && $this->modeEdit ? 'edit' : 'add') ?>&<?php echo $this->additionalParams ?>" name="form_<?php echo $this->name ?>" id="form_<?php echo $this->name ?>">
    <div class="<?php echo isset($this->noModal) ? $this->noModal : ''; ?>modal-body">

<?php
    if (isset($this->noModal) && $this->noModal == "no") {
?>
        <fieldset>
            <legend>Informations générales</legend>
<?php
    }
?>

<?php
    foreach ($this->config["columns"] as $key => $column) {
        if (isset($column["creable_field"])) {
?>
            <div class="control-group">
<?php
                        if (isset($column["creable_field"]["type"])) {
?>
                <label for="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" class="control-label"><?php echo $column["title"]; ?>
<?php
            if (isset($column["creable_field"]["validate"])
                && isset($column["creable_field"]["validate"]["rules"]["required"])
                && $column["creable_field"]["validate"]["rules"]["required"]
            ) {
?>
                    <span class="required">*</span>
<?php
            }
?>
                </label>
<?php
            $value = isset($this->data[$column["name"]]) ? $this->data[$column["name"]] : "";
                switch ($column["creable_field"]["type"]) {
                    case "text":
?>

                <input type="text" class="input-xlarge" value="<?php echo $value; ?>" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>" />
<?php
                        break;

                    case "textarea":
                    case "wysiwyg":
?>

                <textarea row="3" class="input-xlarge<?php echo $column["creable_field"]["type"] == 'wysiwyg' ? ' tiny' : ''; ?>" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>"><?php echo $value; ?></textarea>
<?php
                        break;

                    case "password":
?>

                <input type="password" class="input-xlarge" value="" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>" />
<?php
                        break;

                    case "file":
?>

                <div id="btn-file-upload-<?php echo $this->name ?>-<?php echo $column["name"]; ?>" class="btn-a gradient-green btn-file-upload">
                    <a>Parcourir ...</a>
                </div>
                <a target="_blank" href="<?php echo $column["creable_field"]["http_link"] . $value; ?>"><?php echo $value; ?></a>
                <input type="hidden" value="<?php echo $value; ?>" id="<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>" />
<?php
                        break;

                    case "checkbox":
?>

                <input type="checkbox" class="input-xlarge" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" <?php echo $value == 1 ? 'checked' : ''; ?> value="1" name="<?php echo $column["name"]; ?>" />
<?php
                        break;

                    case "select":
                        if (isset($column["creable_field"]["load"]) && $column["creable_field"]["load"] == true) {
?>

                <select data-value="<?php echo $value; ?>" data-column-key="<?php echo $key; ?>" data-url="<?php echo $this->url; ?><?php echo strpos($this->url, "?") === false ? '?' : '&' ?>select_load&nomain=1" class="ui-select ui-select-load" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>">
                </select>
<?php
                        } elseif (isset($column["creable_field"]["options"]) && is_array($column["creable_field"]["options"])) {
?>
                <select class="ui-select" id="<?php echo $this->name ?>-<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>">
<?php
                            foreach ($column["creable_field"]["options"] as $option) {
?>
                    <option value="<?php echo $option["value"]; ?>" <?php echo $value == $option["value"] ? 'selected="selected"' : ''; ?>><?php echo $option["text"]; ?></option>
<?php
                            }
?>
                </select>
<?php
                        }
                        break;

                    case "multi-autocomplete":
?>

                <input name="<?php echo $column["name"]; ?>" data-column-key="<?php echo $key; ?>" type="text" data-url="<?php echo $this->url; ?><?php echo strpos($this->url, "?") === false ? '?' : '&' ?>multi_autocomplete=1&nomain=1" data-join-table="utilisateur" data-join-field-label="email" data-join-field-id="id" class="autocomplete-multi input-xlarge" />
                <input type="hidden" class="prepopulate" value="<?php echo $value; ?>" />
<?php
                        break;

                    default:
                        break;
                }
            }
?>
            </div>
<?php
        }
    }

    if (isset($this->noModal) && $this->noModal == "no") {
?>
        </fieldset>
<?php
    }

    echo $this->_additionalForm;
?>
        <input type="hidden" name="add" value="<?php echo (!isset($this->modeEdit) || $this->modeEdit == false) ? 1 : 0; ?>" />

    </div>


    <div class="<?php echo isset($this->noModal) ? $this->noModal : ''; ?>modal-footer">
        <a data-dismiss="modal" class="btn btn-small btn-default btn-cancel" aria-hidden="true" href="#"><i class="icon-remove"></i> Annuler</a>
        <a class="btn  btn-small btn-primary btn-success" id="add-<?php echo $this->name ?>" href="#"><i class="icon-ok"></i> <?php echo (isset($this->modeEdit) && $this->modeEdit ? 'Modifier' : 'Ajouter') ?></a>
    </div>

</form>