<div class="btn-a gradient-green btn-append">
    <a href="#">Ajouter un<?php echo $this->config["table"]["suffix_genre"] ?> <?php echo $this->config["table"]["title_item"] ?></a>
</div>
<hr />
<div class="dialog-append" style="display: none;">
    <form>
        <?php
        foreach ($this->config["columns"] as $key => $column) {
            if (isset($column["creable_field"])) {
                if (isset($column["creable_field"]["type"])) {
                    switch ($column["creable_field"]["type"]) {
                        case "text":
                            ?>
                            <div class="line">
                                <label for="<?php echo $column["name"]; ?>"><b><?php echo $column["title"]; ?></b></label>
                                <input type="text" id="<?php echo $column["name"]; ?>" name="<?php echo $column["name"]; ?>" />
                            </div>

                            <?php
                            break;

                        default:
                            break;
                    }
                }
            }
        }
        ?>
    </form>
</div>

<script type="text/javascript">
    
    $(document).ready(function() {
        var dialogAppend = $(".dialog-append").dialog({
            height: "auto",
            width: "auto",
            show: {
                effect:   "fade",
                duration: 1000
            },
            hide: {
                effect:   "fade",
                duration: 500
            },
            open: function(){
                if(!$('.ui-dialog-buttonset button').hasClass("btn"))
                    $('.ui-dialog-buttonset button').attr("class", "").addClass("btn gradient-blue").unbind('mouseout keyup mouseup hover mouseenter mouseover focusin focusout mousedown focus').wrapInner("<a></a>");
            },
            title : "Ajouter un<?php echo $this->config["table"]["suffix_genre"] ?> <?php echo $this->config["table"]["title_item"] ?>",
            resizable : false,
            buttons: {
                "Ok" : function(){
                    var data = $(".dialog-append").find("form").serialize();
                    $.post('<?php echo $this->url; ?><?php echo strpos($this->url, "?") === false ? '?' : '&' ?>add&<?php echo $this->additionalParams ?>', data, function() {
                        dialogAppend.dialog("widget").css({"visibilty" : "hidden"}).effect("transfer", {
                            to: $("#tableau-<?php echo $this->name ?>"),
                            className: "ui-effects-transfer"
                        }, 500, function() {
                            dialogAppend.dialog("close")
                            oTable_<?php echo $this->name ?>.fnDraw(); 
                        });
                        
                        
                    })
                    
                },
                "Annuler" : function(){
                    $(this).dialog("close");
                }
            },
            autoOpen : false,
            close: function(event, ui){
            }
        });  
        
        $('.btn-append').live('click', function(e){
            e.preventDefault()
            dialogAppend.dialog('close');	
            dialogAppend.dialog('open');
            $(this).effect("transfer", {
                to: dialogAppend.dialog("widget"),
                className: "ui-effects-transfer"
            }, 500);
        })
        
    })
</script>