<fieldset><legend><?php echo $this->gabarit->getName(); ?></legend>
    <div style="display:none;">
    <?php
    foreach ($this->champs as $champ) {
        $id_champ = (isset($this->meta['id_version']) ? $this->meta['id_version'] : '') . (isset($value['id']) ? $value['id'] : 0);
        $form = $this->_buildChamp($champ, $this->values, $id_champ, $this->idGabPage, $this->gabarit);
        echo $form["html"];
    }
    ?>
    </div>
</fieldset>