<div class="line form-group">
    <label class="col-sm-2 control-label" for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(' ', $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>

    <div class="col-sm-10 field-file">
        <?php
        $style = $src = $minSrc = $size = $href = '';
        if ($this->value == '') {
            $style = ' display:none;';
        } else {
            $ext  = pathinfo($this->value, PATHINFO_EXTENSION);
            $href = $this->idGabPage . '/' . $this->value;
            $path = 'upload/' . $href;
            if (\Solire\Lib\Model\FileManager::isImage($path)) {
                $minSrc = $this->idGabPage . '/mini/' . $this->value;
                $sizes  = getimagesize('upload/' . $href);
                $size   = $sizes[0] . ' x ' . $sizes[1];
            } else {
                $size   = \Solire\Lib\Format\Number::formatSize(filesize($path));
                $minSrc = 'public/default/back/img/filetype/' . $ext . '.png';
            }
        }
        ?>
        <div class="row field-file-info">
            <div class="col-sm-4">
                <a class="field-file-link exec-onclick-zoom" data-zoom-src="<?php echo $href; ?>" style="<?php echo $style; ?>"
                   href="<?php echo $href; ?>">
                    <img src="<?php echo $minSrc; ?>" class="img-thumbnail img-responsive field-file-thumbnail">
                </a>
            </div>
            <div class="col-sm-8">
                <dl class="dl-horizontal">
                    <dt>Nom de fichier</dt>
                    <dd class="field-file-value"><span><?php echo $this->value; ?></span></dd>

                    <dt>Taille</dt>
                    <dd class="field-file-size"><?php echo $size; ?></dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-sm-offset-2  col-sm-10">
        <div class="input-group select2-bootstrap-append">
            <select
                style="width: 100%"
                data-amd="modules/helper/autocompleteFile"
                data-min-width="<?php echo $this->params["CROP.WIDTH.MIN"]; ?>"
                data-min-height="<?php echo $this->params["CROP.HEIGHT.MIN"]; ?>"
                data-extensions="<?php echo $this->params["EXTENSIONS.ALLOW"]; ?>"
                type="text"
                name="champ<?php echo $this->champ['id']; ?>[]"
                id="<?php echo $this->id; ?>"
                class="<?php echo $this->classes; ?> form-control"
                value="<?php echo $this->value; ?>"
                data-visuel-id="<?php echo $this->champ['id']; ?>">
                <?php if ($this->value) {
                    ?>
                    <option value="<?php echo $this->value; ?>" selected="selected"><?php echo $this->value; ?></option>
                    <?php
                }
                ?>
            </select>
            <span class="input-group-btn">
                <a title="Recadrer" <?php echo $this->isImage ? '' : 'style="display:none;"' ?>
                   data-amd="modules/helper/cropDialog"
                   class="btn btn-sm btn-info field-file-crop" href="#">
                    <i class="fa fa-crop"></i>
                </a>
                <a href="#" class="btn btn-sm btn-primary" title="Importer un fichier">
                    <i class="fa fa-folder-open"></i>
                </a>
            </span>
        </div>
    </div>
    <input type="hidden" class="extensions" value="<?php echo $this->params["EXTENSIONS.ALLOW"]; ?>"/>
</div>
