<div class="line form-line">
    <div class="line">
        <label for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
        </label>
        <textarea name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?>" rows="5" cols="20"><?php echo $this->value; ?></textarea>
    </div>

    <div class="line form-other-line" style="display:none;">
        <label class="form-other-flag"></label>
        <textarea readonly="readonly" class="form-other-elmt"></textarea>
    </div>
</div>
