<div class="line">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>
    <input type="text" value="<?php echo $this->value; ?>" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class=" autocomplete-multi" />
    <input type="hidden" class="join-param join-table" value="<?php echo $this->params["TABLE.NAME"]; ?>" />
    <input type="hidden" class="join-param join-label_field" value="<?php echo $this->params["TABLE.FIELD.LABEL"]; ?>" />
    <input type="hidden" class="join-param join-query_filter" value="<?php echo $this->params["QUERY.FILTER"]; ?>" />
    <input type="hidden" class="join-param join-id_field" value="<?php echo $this->params["TABLE.FIELD.ID"]; ?>" />
    <input type="hidden" class="join-param automplete_multi-theme" value="<?php echo $this->params["THEME"]; ?>" />
    <input type="hidden" class="prepopulate" value="<?php echo $this->values; ?>" />
</div>
