<div class="line">
    <label for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>
    <input type="checkbox" class="js-checkbox" id="<?php echo $this->id; ?>"<?php echo ($this->value > 0 ? ' checked="checked"' : ''); ?> />
    <input type="hidden" name="champ<?php echo $this->champ['id']; ?>[]" value="<?php echo $this->value; ?>" />
</div>