<div class="line form-line">
    <div class="line">
        <label for="<?php echo $this->id; ?>">
            <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(" ", $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
        </label>

        <div class="btn-group switch-editor">
            <a href="#" class="btn btn-small btn-default">mode html</a>
            <a href="#" class="btn btn-small btn-info">mode texte</a>
        </div>

        <div style="clear:both;"></div>

        <textarea name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="<?php echo $this->classes; ?> tiny" rows="5" cols="20" style="width:100%; height:325px;"><?php echo $this->value; ?></textarea>
    </div>

    <div class="line form-other-line" style="display:none;">
        <label class="form-other-flag"></label>
        <span style="display:inline-block; width: 500px; height: 290px; border-left:1px solid #CCC; border-right:1px solid #CCC; border-top:1px solid #CCC; border-bottom:1px solid #CCC;">
            <iframe style="width:100%; height:100%" class="form-other-elmt"></iframe>
        </span>
    </div>
</div>
