<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Erreur Interne :(</title>
  <style>
	  body { text-align: center;}
	  h1 { font-size: 50px; text-align: center }
	  span[frown] { transform: rotate(90deg); display:inline-block; color: #bbb; }
	  body { font: 20px Constantia, 'Hoefler Text',  "Adobe Caslon Pro", Baskerville, Georgia, Times, serif; color: #999; text-shadow: 2px 2px 2px rgba(200, 200, 200, 0.5); }
	  ::-moz-selection{ background:#64C81E; color:#fff; }
	  ::selection { background:#64C81E; color:#fff; }
	  article {display:block; text-align: left; width: 500px; margin: 0 auto; }

	  a { color: rgb(36, 109, 56); text-decoration:none; }
	  a:hover { color: rgb(96, 73, 141) ; text-shadow: 2px 2px 2px rgba(36, 109, 56, 0.5); }
  </style>
</head>
<body>
     <article>
	  <h1>Oups... <span frown>:(</span></h1>
	   <div>
	       <p>Une erreur est survenue pendant l'affichage de la page.</p>
	   </div>

	    <script>
	    var GOOG_FIXURL_LANG = 'fr',
		GOOG_FIXURL_SITE = "<?php echo self::$_config->get('url', 'base'); ?>";
	    </script>
	    <script src="http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"></script>
     </article>
</body>
</html>