<div class="line">
<?php
    foreach ($this->allValues as $value) {
        $groups[strtolower($value["label"][0])][] = $value;
    }
    ksort($groups);
    foreach ($groups as $c => $v) {
        if (isset($groups[$c])) {
?>
    <div style="float:left;width: 33%;margin-bottom: 15px;" >
<?php
        echo strtoupper($c);

        foreach ($groups[$c] as $value) {
            $checked = in_array($value["id"], $this->values);
?>
                <div>
                    <input style="" class="join-simple" <?php echo $checked ? 'checked="checked"' : ''; ?> type="checkbox" value="<?php echo $value["id"]; ?>" name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id . $value["id"]; ?>" class="<?php echo $this->classes; ?> join" />
                    <label style="margin-left:0;display: inline;float:none;" for="<?php echo $this->id . $value["id"]; ?>"><?php echo $value["label"]; ?></label>
                </div>
<?php
        }
?>
    </div>
<?php
        }
    }
?>
</div>
