<div class="line form-group" data-toggle="popover" data-trigger="hover" title="Aide" data-html="true"  data-popover-content="#aide-champ<?php echo $this->champ['id']; ?>">
    <label class="col-sm-3 control-label" for="<?php echo $this->id; ?>">
        <span><?php echo $this->label; ?> <?php echo in_array('form-oblig', explode(' ', $this->classes)) ? '<span class="required">*</span> ' : '' ; ?></span>
    </label>
    <div class="col-sm-9">
        <select name="champ<?php echo $this->champ['id']; ?>[]" id="<?php echo $this->id; ?>" class="form-control <?php echo $this->classes; ?>">
            <option value="">---</option>
<?php
    foreach ($this->values as $value) {
?>
            <option <?php echo $this->value == $value ? 'selected="selected"' : ''; ?> value="<?php echo $value; ?>"><?php echo $value; ?></option>
<?php
    }
?>
        </select>
    </div>
</div>