<style>
    .table th, .table td {
        border-top: 1px solid #DDDDDD;
        line-height: 20px;
        padding: 8px;
        text-align: left;
        vertical-align: top;
        border-left: 0px;
    }

    .bar {
        -webkit-transition: width 0.1s ease !important;
        -moz-transition: width 0.1s ease !important;
        -o-transition: width 0.1s ease !important;
        transition: width 0.1s ease !important;
    }

    .progress {
        margin: 0;
    }

    .dt-action {
        text-align: right;
    }

</style>

<h1>Détails <?php echo $this->config["table"]["title_item"] ?></h1>

<?php echo $this->_beforeHTML; ?>



<div class="">
    <div class="dt-action">
        <?php
        if (isset($this->config["extra"])
                && isset($this->config["extra"]["editable"]) && $this->config["extra"]["editable"]
                && isset($this->config["form"])
                && isset($this->config["form"]["ajax"])
                && $this->config["form"]["ajax"] == false) {
            ?>

            <a href="<?php echo $this->url . '&dt_action=formEditRender&index=' . $_GET["index"]; ?>" title="Modifier" class="btn btn-success edit-item-no-ajax">
                <img width="12" src="img/back/white/pen_alt_stroke_12x12.png" alt="Modifier" />
            </a>

            <?php
        }
        ?>
    </div>


    <?php
    $realIndex = 0;
    foreach ($this->config["columns"] as $key => $column) {
        ?>
        <?php
        if (((isset($column["show"]) && $column["show"]) || (isset($column["show_detail"]) && $column["show_detail"]))) {
            
            $value = isset($this->data[$realIndex]) ? $this->data[$realIndex] : "";
            if ($value != "" && (!isset($column["show_page_detail"]) || $column["show_page_detail"] == true)) {
                ?>

                <h2 style="margin-bottom: 0"><?php echo $column["title"]; ?></h2>
                <blockquote style="margin-left:20px;margin-bottom: 0px;">

                    <p><?php echo $value; ?></p>


                </blockquote>
                <?php
            }
            
            $realIndex++;
        }
    }
    ?>

</div>


<?php
if (!isset($_GET["nojs"]) || !$_GET["nojs"]) {
    echo '
            ' . $this->_css . '
            ' . $this->_javascript;
}
?>


